# HoloSyn: Multimodal P2P Co‑Regulation — Open‑Source Hugging Face Teacher Distillation (Colab)

Runs locally using **open-source Hugging Face models** (no API keys).

Pipeline:
1. Extract audio/video/image/text/haptics from `Archive.zip`
2. Run **teacher inference** with open-source models
3. Map teacher outputs → targets: `valence, arousal, calm, trust` (0..1)
4. Train a compact **student head** and export **TorchScript**
5. Optional runtime: **Cirq/qsimcirq** synchrony + **Brian2** entrainment

In [2]:
#@title 0) Install dependencies
!pip -q install -U numpy pandas tqdm pillow opencv-python soundfile librosa
!pip -q install -U torch torchvision torchaudio
!pip -q install -U transformers accelerate sentencepiece safetensors
!pip -q install -U cirq qsimcirq brian2

import os, json, zipfile
import numpy as np
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from PIL import Image
import torch
print("✅ Installed.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 65.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 59.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cirq-core 1.6.1 requires pandas~=2.1, but you have pandas 3.0.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.1.1 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 46.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.1.1 which is incompatible.
✅ Installed.

In [4]:
#@title 1) Locate and extract Archive.zip
def pick_existing(*cands):
    for c in cands:
        if c and os.path.exists(c):
            return c
    return None

ARCHIVE_ZIP = pick_existing("/mnt/data/Archive.zip", "/content/Archive.zip")
assert ARCHIVE_ZIP, "❌ Archive.zip not found. Upload it to Colab Files or place in /mnt/data."

EXTRACT_DIR = "/content/archive_extracted"
Path(EXTRACT_DIR).mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ARCHIVE_ZIP, "r") as z:
    z.extractall(EXTRACT_DIR)

print("ARCHIVE_ZIP:", ARCHIVE_ZIP)
print("EXTRACT_DIR:", EXTRACT_DIR)
print("Top-level:")
for p in sorted(Path(EXTRACT_DIR).iterdir())[:60]:
    print(" -", p.name, "(dir)" if p.is_dir() else "(file)")

ARCHIVE_ZIP: /content/Archive.zip
EXTRACT_DIR: /content/archive_extracted
Top-level:
 - E_aud.npy (file)
 - E_img.npy (file)
 - E_text.npy (file)
 - E_vid.npy (file)
 - audio (dir)
 - haptics (dir)
 - images (dir)
 - manifest.jsonl (file)
 - text (dir)
 - video (dir)

In [5]:
#@title 2) Discover files by modality
AUDIO_EXT = {".wav",".mp3",".m4a",".flac",".ogg",".aac"}
VIDEO_EXT = {".mp4",".mov",".mkv",".webm",".avi"}
IMAGE_EXT = {".png",".jpg",".jpeg",".webp",".bmp"}
TEXT_EXT  = {".txt",".md",".json",".csv",".tsv"}

def walk_files(root):
    out=[]
    for p in Path(root).rglob("*"):
        if p.is_file(): out.append(str(p))
    return out

def bucket(path):
    ext = Path(path).suffix.lower()
    low = path.lower()
    if ext in AUDIO_EXT: return "audio"
    if ext in VIDEO_EXT: return "video"
    if ext in IMAGE_EXT: return "image"
    if ext in TEXT_EXT:
        if ext in {".json",".csv",".tsv"} and any(k in low for k in ["hapt","vib","pattern","tact","rumble"]):
            return "haptics"
        return "text"
    if any(k in low for k in ["hapt","vib","pattern","tact","rumble"]):
        return "haptics"
    return "other"

all_files = walk_files(EXTRACT_DIR)
buckets={}
for f in all_files:
    buckets.setdefault(bucket(f), []).append(f)

for k in ["audio","video","image","text","haptics","other"]:
    print(f"{k:8s}", len(buckets.get(k, [])))
    for s in buckets.get(k, [])[:3]:
        print("   •", s.replace(EXTRACT_DIR + "/", ""))

audio    49
   • audio/model_c000002_0000004.wav
   • audio/cookie_c000003_0000025.wav
   • audio/cookie_c000002_0000012.wav
video    50
   • video/cookie_c000003_0000024.mp4
   • video/model_c000002_0000006.mp4
   • video/model_c000003_0000033.mp4
image    115
   • images/kenzonaplane-20260216-0052.jpg
   • images/client_c000002_0000015.png
   • images/kenzonaplane-20260216-0059.jpg
text     49
   • text/client_c000002_0000017.txt
   • text/model_c000002_0000004.txt
   • text/blockheart_c000001_0000048.txt
haptics  67
   • haptics/0007.npy
   • haptics/0001.npy
   • haptics/0034.npy
other    5
   • E_vid.npy
   • E_text.npy
   • manifest.jsonl

In [6]:
#@title 3) Local features (privacy-preserving)
import librosa, cv2

def rel(p): return p.replace(EXTRACT_DIR + "/", "")
def load_text(path, max_chars=12000):
    return open(path, "r", encoding="utf-8", errors="ignore").read()[:max_chars]

def load_haptics_any(path):
    ext = Path(path).suffix.lower()
    if ext == ".json":
        try: return json.load(open(path, "r", encoding="utf-8", errors="ignore"))
        except: return {"raw": load_text(path)}
    if ext in {".csv",".tsv"}:
        sep = "," if ext==".csv" else "\t"
        try:
            df = pd.read_csv(path, sep=sep)
            return {"columns": list(df.columns), "head": df.head(200).to_dict(orient="list")}
        except:
            return {"raw": load_text(path)}
    return {"raw": load_text(path)}

def featurize_text(s):
    return {"txt_len":float(len(s)),
            "txt_lines":float(s.count("\n")+1),
            "txt_exclaim":float(s.count("!")),
            "txt_question":float(s.count("?")),
            "txt_caps_ratio":float(sum(c.isupper() for c in s)/max(1,len(s)))}

def featurize_haptics(h):
    raw = json.dumps(h)[:20000].lower()
    return {"hapt_len":float(len(raw)),
            "hapt_has_intensity":1.0 if "intensity" in raw else 0.0,
            "hapt_has_freq":1.0 if ("hz" in raw or "freq" in raw) else 0.0}

def audio_features(path, sr=16000, max_seconds=15):
    y, _ = librosa.load(path, sr=sr, mono=True, duration=max_seconds)
    if y.size < 10:
        return {"aud_rms":0.0,"aud_zcr":0.0,"aud_centroid":0.0,"aud_tempo":0.0}
    rms = float(np.mean(librosa.feature.rms(y=y)))
    zcr = float(np.mean(librosa.feature.zero_crossing_rate(y)))
    centroid = float(np.mean(librosa.feature.spectral_centroid(y=y, sr=sr)))
    onset_env = librosa.onset.onset_strength(y=y, sr=sr)
    tempo = float(librosa.beat.tempo(onset_envelope=onset_env, sr=sr)[0]) if onset_env.size else 0.0
    return {"aud_rms":rms,"aud_zcr":zcr,"aud_centroid":centroid,"aud_tempo":tempo}

def image_quick_stats(path):
    im = Image.open(path).convert("RGB")
    arr = np.asarray(im).astype(np.float32)/255.0
    mean = arr.mean(axis=(0,1))
    std = arr.std(axis=(0,1))
    return {"img_w":float(arr.shape[1]),"img_h":float(arr.shape[0]),
            "img_mean_r":float(mean[0]),"img_mean_g":float(mean[1]),"img_mean_b":float(mean[2]),
            "img_std_r":float(std[0]),"img_std_g":float(std[1]),"img_std_b":float(std[2])}

def sample_video_frames(video_path, every_n_frames=45, max_frames=4, target_size=224):
    cap = cv2.VideoCapture(video_path)
    frames=[]
    idx=0
    while cap.isOpened() and len(frames) < max_frames:
        ret, frame = cap.read()
        if not ret: break
        if idx % every_n_frames == 0:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            h,w = frame.shape[:2]
            if max(h,w) > target_size:
                scale = target_size / max(h,w)
                frame = cv2.resize(frame, (int(w*scale), int(h*scale)))
            frames.append(frame)
        idx += 1
    cap.release()
    return frames

MAX_PER_MODALITY = 250
rows=[]
for p in tqdm(buckets.get("text", [])[:MAX_PER_MODALITY], desc="text"):
    rows.append({"path":p,"rel":rel(p),"modality":"text",**featurize_text(load_text(p))})
for p in tqdm(buckets.get("haptics", [])[:MAX_PER_MODALITY], desc="haptics"):
    rows.append({"path":p,"rel":rel(p),"modality":"haptics",**featurize_haptics(load_haptics_any(p))})
for p in tqdm(buckets.get("audio", [])[:MAX_PER_MODALITY], desc="audio"):
    rows.append({"path":p,"rel":rel(p),"modality":"audio",**audio_features(p)})
for p in tqdm(buckets.get("image", [])[:MAX_PER_MODALITY], desc="image"):
    try: rows.append({"path":p,"rel":rel(p),"modality":"image",**image_quick_stats(p)})
    except Exception as e: print("skip image", rel(p), e)
for p in tqdm(buckets.get("video", [])[:MAX_PER_MODALITY], desc="video"):
    try: rows.append({"path":p,"rel":rel(p),"modality":"video","vid_n_frames":float(len(sample_video_frames(p)))})
    except Exception as e: print("skip video", rel(p), e)

df = pd.DataFrame(rows).fillna(0.0)
print("✅ Base features:", df.shape)
df.head()

text: 100%|██████████| 49/49 [00:00<00:00, 5780.04it/s]
haptics: 100%|██████████| 67/67 [00:00<00:00, 4589.03it/s]
audio:   0%|          | 0/49 [00:00<?, ?it/s]/tmp/ipython-input-2621360028.py:43: FutureWarning: librosa.beat.tempo
	This function was moved to 'librosa.feature.rhythm.tempo' in librosa version 0.10.0.
	This alias will be removed in librosa version 1.0.
  tempo = float(librosa.beat.tempo(onset_envelope=onset_env, sr=sr)[0]) if onset_env.size else 0.0
audio: 100%|██████████| 49/49 [00:34<00:00,  1.43it/s]
image: 100%|██████████| 115/115 [00:17<00:00,  6.68it/s]
video: 100%|██████████| 50/50 [00:00<00:00, 50.90it/s]

✅ Base features: (330, 24)

,path,rel,modality,txt_len,txt_lines,txt_exclaim,txt_question,txt_caps_ratio,hapt_len,hapt_has_intensity,...,aud_tempo,img_w,img_h,img_mean_r,img_mean_g,img_mean_b,img_std_r,img_std_g,img_std_b,vid_n_frames
0,/content/archive_extracted/text/client_c000002...,text/client_c000002_0000017.txt,text,104.0,1.0,0.0,0.0,0.057692,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/content/archive_extracted/text/model_c000002_...,text/model_c000002_0000004.txt,text,103.0,1.0,0.0,0.0,0.058252,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/content/archive_extracted/text/blockheart_c00...,text/blockheart_c000001_0000048.txt,text,106.0,1.0,0.0,0.0,0.056604,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/content/archive_extracted/text/model_c000004_...,text/model_c000004_0000036.txt,text,101.0,1.0,0.0,0.0,0.059406,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/content/archive_extracted/text/model_c000004_...,text/model_c000004_0000034.txt,text,103.0,1.0,0.0,0.0,0.058252,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
#@title 4) Load open-source teachers (HF)
!pip install -q -U pillow==9.5.0
from transformers import pipeline, AutoProcessor, AutoModel
import torch

device = 0 if torch.cuda.is_available() else -1
print("device:", "cuda" if device==0 else "cpu")

EMO_MODEL = "j-hartmann/emotion-english-distilroberta-base"
SENT_MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
CLIP_MODEL = "openai/clip-vit-base-patch32"
W2V_MODEL  = "facebook/wav2vec2-base-960h"

emo_pipe = pipeline("text-classification", model=EMO_MODEL, top_k=None, device=device)
sent_pipe = pipeline("text-classification", model=SENT_MODEL, top_k=None, device=device)

clip_processor = AutoProcessor.from_pretrained(CLIP_MODEL)
clip_model = AutoModel.from_pretrained(CLIP_MODEL).to("cuda" if device==0 else "cpu").eval()

w2v_processor = AutoProcessor.from_pretrained(W2V_MODEL)
w2v_model = AutoModel.from_pretrained(W2V_MODEL).to("cuda" if device==0 else "cpu").eval()

print("✅ Teachers loaded")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 MB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for pillow (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-image 0.25.2 requires pillow>=10.1, but you have pillow 9.5.0 which is incompatible.
device: cpu

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |
roberta.pooler.dense.bias       | UNEXPECTED |  |
roberta.pooler.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/592 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: openai/clip-vit-base-patch32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/210 [00:00<?, ?it/s]

Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base-960h
Key               | Status     |
------------------+------------+-
lm_head.weight    | UNEXPECTED |
lm_head.bias      | UNEXPECTED |
masked_spec_embed | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

✅ Teachers loaded

In [10]:
#@title 5) Teacher cache: targets + embeddings
def softmax_dict(items):
    d = {it["label"].lower(): float(it["score"]) for it in items}
    s = sum(d.values()) or 1.0
    return {k:v/s for k,v in d.items()}

def emotion_to_targets(emo_probs, sent_probs):
    valence = sent_probs.get("positive",0.33) + 0.5*sent_probs.get("neutral",0.33)
    valence = float(np.clip(valence,0,1))
    arousal = (
        1.0*emo_probs.get("anger",0) +
        1.0*emo_probs.get("fear",0) +
        0.8*emo_probs.get("surprise",0) +
        0.6*emo_probs.get("joy",0) +
        0.2*emo_probs.get("sadness",0) +
        0.3*emo_probs.get("disgust",0)
    )
    arousal = float(np.clip(arousal,0,1))
    calm = float(np.clip(1.0-arousal,0,1))
    trust = float(np.clip(valence*(1.0-0.8*emo_probs.get("fear",0)-0.6*emo_probs.get("anger",0)),0,1))
    return valence, arousal, calm, trust

@torch.no_grad()
def clip_image_embedding(pil_images):
    if not isinstance(pil_images, list): pil_images=[pil_images]
    inputs = clip_processor(images=pil_images, return_tensors="pt")
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    inputs = {k:v.to(dev) for k,v in inputs.items()}
    out = clip_model.get_image_features(**inputs)
    out = out / out.norm(dim=-1, keepdim=True)
    return out.cpu().numpy()

@torch.no_grad()
def wav2vec_embedding(wav_path, sr=16000, max_seconds=10):
    y, _ = librosa.load(wav_path, sr=sr, mono=True, duration=max_seconds)
    if y.size < 10:
        return np.zeros((768,), dtype=np.float32)
    inputs = w2v_processor(y, sampling_rate=sr, return_tensors="pt")
    dev = "cuda" if torch.cuda.is_available() else "cpu"
    inputs = {k:v.to(dev) for k,v in inputs.items()}
    out = w2v_model(**inputs).last_hidden_state
    emb = out.mean(dim=1).squeeze(0)
    emb = emb / (emb.norm() + 1e-8)
    return emb.detach().cpu().numpy().astype(np.float32)

CACHE_PATH="/content/hf_teacher_cache.parquet"
teacher_df = pd.read_parquet(CACHE_PATH) if os.path.exists(CACHE_PATH) else pd.DataFrame()
done=set(teacher_df["rel"].tolist()) if len(teacher_df) else set()

records=[]
N_PER_MODALITY=180

# text/haptics targets
for modality in ["text","haptics"]:
    sub = df[df["modality"]==modality].head(N_PER_MODALITY)
    for _, row in tqdm(sub.iterrows(), total=len(sub), desc=f"teacher {modality}"):
        if row["rel"] in done: continue
        try:
            txt = load_text(row["path"]) if modality=="text" else ("HAPTICS_JSON:\n"+json.dumps(load_haptics_any(row["path"]))[:12000])
            emo = emo_pipe(txt[:3000])[0]
            sent = sent_pipe(txt[:3000])[0]
            emo_probs, sent_probs = softmax_dict(emo), softmax_dict(sent)
            v,a,c,t = emotion_to_targets(emo_probs, sent_probs)
            records.append({"rel":row["rel"],"modality":modality,"valence":v,"arousal":a,"calm":c,"trust":t})
        except Exception as e:
            print("skip", row["rel"], e)

# image/video clip embeddings
for modality in ["image","video"]:
    sub = df[df["modality"]==modality].head(N_PER_MODALITY)
    for _, row in tqdm(sub.iterrows(), total=len(sub), desc=f"teacher {modality}"):
        if row["rel"] in done: continue
        try:
            if modality=="image":
                ims=[Image.open(row["path"]).convert("RGB")]
            else:
                frames=sample_video_frames(row["path"])
                if not frames: continue
                ims=[Image.fromarray(f).convert("RGB") for f in frames]
            embs=clip_image_embedding(ims)
            emb=embs.mean(axis=0)
            emb=emb/(np.linalg.norm(emb)+1e-8)
            records.append({"rel":row["rel"],"modality":modality,
                            "valence":0.5,"arousal":0.5,"calm":0.5,"trust":0.5,
                            "clip_emb":emb.tolist()})
        except Exception as e:
            print("skip", modality, row["rel"], e)

# audio wav2vec embedding
sub = df[df["modality"]=="audio"].head(N_PER_MODALITY)
for _, row in tqdm(sub.iterrows(), total=len(sub), desc="teacher audio"):
    if row["rel"] in done: continue
    try:
        emb=wav2vec_embedding(row["path"])
        records.append({"rel":row["rel"],"modality":"audio",
                        "valence":0.5,"arousal":0.5,"calm":0.5,"trust":0.5,
                        "w2v_emb":emb.tolist()})
    except Exception as e:
        print("skip audio", row["rel"], e)

new_df=pd.DataFrame(records)
teacher_df = pd.concat([teacher_df, new_df], ignore_index=True) if len(teacher_df) else new_df
teacher_df.to_parquet(CACHE_PATH, index=False)
print("✅ Teacher cache:", teacher_df.shape, "saved to", CACHE_PATH)
teacher_df.head()

teacher text: 100%|██████████| 49/49 [00:28<00:00,  1.74it/s]
teacher haptics:   0%|          | 0/67 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (2313 > 512). Running this sequence through the model will result in indexing errors
teacher haptics:  24%|██▍       | 16/67 [00:00<00:00, 88.73it/s]

skip haptics/0007.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0001.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0034.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0014.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0020.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmplfehff5d.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0045.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpq3e7wy9g.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0038.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0027.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0000.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0006.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0029.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0025.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0017.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0019.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpfc9cgktu.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpfxqqwrkj.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0009.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0040.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0002.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0022.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0041.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpesoasc75.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0032.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0039.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0033.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmplrn5lm5k.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0011.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0004.npy index 514 is out of bounds for dimension 1 with size 514

teacher haptics:  70%|███████   | 47/67 [00:00<00:00, 130.74it/s]

skip haptics/0047.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0005.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0044.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0035.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0010.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0048.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0030.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0026.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmp9rqdlj5p.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0043.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmp9df1uhrn.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmptxjm61l_.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0021.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmphgankhv1.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0003.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0016.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0042.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpwwi5tm4p.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0024.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0015.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0013.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpe8qoq90v.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0012.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0037.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpznmcwho3.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmp4byvypa2.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmpvzul2gx_.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0031.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0028.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0036.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmp591wxgrj.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/tmp74jokr7g.npy index 514 is out of bounds for dimension 1 with size 514

teacher haptics: 100%|██████████| 67/67 [00:00<00:00, 119.70it/s]

skip haptics/tmp790ip2wt.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0008.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0023.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0018.npy index 514 is out of bounds for dimension 1 with size 514
skip haptics/0046.npy index 514 is out of bounds for dimension 1 with size 514

teacher image:   1%|          | 1/115 [00:01<02:52,  1.51s/it]

skip image images/kenzonaplane-20260216-0052.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   2%|▏         | 2/115 [00:01<01:34,  1.20it/s]

skip image images/client_c000002_0000015.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   3%|▎         | 3/115 [00:02<01:12,  1.54it/s]

skip image images/kenzonaplane-20260216-0059.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   3%|▎         | 4/115 [00:02<01:02,  1.78it/s]

skip image images/kenzonaplane-20260216-0046.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   4%|▍         | 5/115 [00:02<00:50,  2.19it/s]

skip image images/model_c000002_0000004.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   5%|▌         | 6/115 [00:03<00:41,  2.62it/s]

skip image images/cookie_c000003_0000026.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   6%|▌         | 7/115 [00:03<00:35,  3.03it/s]

skip image images/cookie_c000002_0000023.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   7%|▋         | 8/115 [00:03<00:33,  3.17it/s]

skip image images/kenzonaplane-20260216-0013.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   8%|▊         | 9/115 [00:04<00:31,  3.32it/s]

skip image images/kenzonaplane-20260216-0053.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:   9%|▊         | 10/115 [00:04<00:31,  3.35it/s]

skip image images/kenzonaplane-20260216-0010.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  10%|▉         | 11/115 [00:04<00:30,  3.43it/s]

skip image images/kenzonaplane-20260216-0014.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  10%|█         | 12/115 [00:04<00:28,  3.56it/s]

skip image images/kenzonaplane-20260216-0012.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  11%|█▏        | 13/115 [00:05<00:26,  3.81it/s]

skip image images/model_c000003_0000020.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  12%|█▏        | 14/115 [00:05<00:27,  3.69it/s]

skip image images/kenzonaplane-20260216-0037.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  13%|█▎        | 15/115 [00:05<00:25,  3.92it/s]

skip image images/cookie_c000001_0000008.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  14%|█▍        | 16/115 [00:05<00:25,  3.85it/s]

skip image images/kenzonaplane-20260216-0030.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  15%|█▍        | 17/115 [00:06<00:25,  3.81it/s]

skip image images/kenzonaplane-20260216-0006.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  16%|█▌        | 18/115 [00:06<00:26,  3.72it/s]

skip image images/kenzonaplane-20260216-0034.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  17%|█▋        | 19/115 [00:06<00:24,  3.95it/s]

skip image images/cookie_c000002_0000012.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  17%|█▋        | 20/115 [00:06<00:24,  3.83it/s]

skip image images/kenzonaplane-20260216-0061.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  18%|█▊        | 21/115 [00:07<00:23,  4.01it/s]

skip image images/model_c000003_0000019.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  19%|█▉        | 22/115 [00:07<00:24,  3.79it/s]

skip image images/kenzonaplane-20260216-0063.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  20%|██        | 23/115 [00:07<00:24,  3.77it/s]

skip image images/kenzonaplane-20260216-0022.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  21%|██        | 24/115 [00:07<00:24,  3.66it/s]

skip image images/kenzonaplane-20260216-0051.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  22%|██▏       | 25/115 [00:08<00:23,  3.84it/s]

skip image images/cookie_c000003_0000038.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  23%|██▎       | 26/115 [00:08<00:23,  3.74it/s]

skip image images/kenzonaplane-20260216-0045.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  23%|██▎       | 27/115 [00:08<00:24,  3.65it/s]

skip image images/kenzonaplane-20260216-0019.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  24%|██▍       | 28/115 [00:09<00:23,  3.67it/s]

skip image images/kenzonaplane-20260216-0035.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  25%|██▌       | 29/115 [00:09<00:22,  3.88it/s]

skip image images/cookie_c000002_0000010.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  26%|██▌       | 30/115 [00:09<00:22,  3.73it/s]

skip image images/kenzonaplane-20260216-0002.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  27%|██▋       | 31/115 [00:09<00:22,  3.72it/s]

skip image images/kenzonaplane-20260216-0056.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  28%|██▊       | 32/115 [00:10<00:20,  3.96it/s]

skip image images/client_c000001_0000013.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  29%|██▊       | 33/115 [00:10<00:19,  4.12it/s]

skip image images/cookie_c000002_0000011.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  30%|██▉       | 34/115 [00:10<00:19,  4.17it/s]

skip image images/cookie_c000004_0000041.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  30%|███       | 35/115 [00:10<00:18,  4.25it/s]

skip image images/model_c000003_0000021.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  31%|███▏      | 36/115 [00:10<00:19,  4.03it/s]

skip image images/kenzonaplane-20260216-0003.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  32%|███▏      | 37/115 [00:11<00:19,  3.97it/s]

skip image images/kenzonaplane-20260216-0044.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  33%|███▎      | 38/115 [00:11<00:19,  4.02it/s]

skip image images/cookie_c000003_0000027.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  34%|███▍      | 39/115 [00:11<00:18,  4.14it/s]

skip image images/cookie_c000003_0000024.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  35%|███▍      | 40/115 [00:11<00:18,  4.06it/s]

skip image images/kenzonaplane-20260216-0047.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  36%|███▌      | 41/115 [00:12<00:17,  4.19it/s]

skip image images/model_c000004_0000036.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  37%|███▋      | 42/115 [00:12<00:18,  3.87it/s]

skip image images/kenzonaplane-20260216-0042.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  37%|███▋      | 43/115 [00:12<00:18,  3.99it/s]

skip image images/client_c000003_0000032.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  38%|███▊      | 44/115 [00:13<00:20,  3.48it/s]

skip image images/kenzonaplane-20260216-0072.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  39%|███▉      | 45/115 [00:13<00:23,  2.97it/s]

skip image images/kenzonaplane-20260216-0066.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  40%|████      | 46/115 [00:13<00:23,  2.89it/s]

skip image images/model_c000003_0000033.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  41%|████      | 47/115 [00:14<00:24,  2.74it/s]

skip image images/kenzonaplane-20260216-0048.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  42%|████▏     | 48/115 [00:14<00:25,  2.63it/s]

skip image images/kenzonaplane-20260216-0011.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  43%|████▎     | 49/115 [00:15<00:26,  2.51it/s]

skip image images/kenzonaplane-20260216-0001.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  43%|████▎     | 50/115 [00:15<00:26,  2.45it/s]

skip image images/kenzonaplane-20260216-0026.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  44%|████▍     | 51/115 [00:16<00:26,  2.38it/s]

skip image images/kenzonaplane-20260216-0018.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  45%|████▌     | 52/115 [00:16<00:22,  2.76it/s]

skip image images/cookie_c000004_0000039.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  46%|████▌     | 53/115 [00:16<00:20,  3.00it/s]

skip image images/kenzonaplane-20260216-0029.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  47%|████▋     | 54/115 [00:16<00:18,  3.31it/s]

skip image images/cookie_c000003_0000025.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  48%|████▊     | 55/115 [00:17<00:16,  3.54it/s]

skip image images/model_c000003_0000022.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  49%|████▊     | 56/115 [00:17<00:15,  3.78it/s]

skip image images/model_c000002_0000005.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  50%|████▉     | 57/115 [00:17<00:15,  3.81it/s]

skip image images/kenzonaplane-20260216-0062.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  50%|█████     | 58/115 [00:17<00:15,  3.78it/s]

skip image images/kenzonaplane-20260216-0050.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  51%|█████▏    | 59/115 [00:18<00:15,  3.64it/s]

skip image images/kenzonaplane-20260216-0004.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  52%|█████▏    | 60/115 [00:18<00:14,  3.67it/s]

skip image images/kenzonaplane-20260216-0028.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  53%|█████▎    | 61/115 [00:18<00:13,  3.89it/s]

skip image images/client_c000001_0000002.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  54%|█████▍    | 62/115 [00:18<00:14,  3.75it/s]

skip image images/kenzonaplane-20260216-0058.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  55%|█████▍    | 63/115 [00:19<00:13,  3.89it/s]

skip image images/cookie_c000004_0000040.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  56%|█████▌    | 64/115 [00:19<00:13,  3.92it/s]

skip image images/client_c000002_0000016.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  57%|█████▋    | 65/115 [00:19<00:12,  3.86it/s]

skip image images/kenzonaplane-20260216-0032.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  57%|█████▋    | 66/115 [00:19<00:12,  4.02it/s]

skip image images/client_c000003_0000031.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  58%|█████▊    | 67/115 [00:20<00:12,  3.86it/s]

skip image images/kenzonaplane-20260216-0054.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  59%|█████▉    | 68/115 [00:20<00:12,  3.75it/s]

skip image images/kenzonaplane-20260216-0064.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  60%|██████    | 69/115 [00:20<00:11,  3.95it/s]

skip image images/model_c000001_0000000.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  61%|██████    | 70/115 [00:20<00:11,  3.81it/s]

skip image images/kenzonaplane-20260216-0071.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  62%|██████▏   | 71/115 [00:21<00:11,  3.92it/s]

skip image images/blockheart_c000001_0000047.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  63%|██████▎   | 72/115 [00:21<00:10,  4.08it/s]

skip image images/cookie_c000004_0000043.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  63%|██████▎   | 73/115 [00:21<00:10,  3.88it/s]

skip image images/kenzonaplane-20260216-0043.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  64%|██████▍   | 74/115 [00:21<00:10,  3.74it/s]

skip image images/kenzonaplane-20260216-0039.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  65%|██████▌   | 75/115 [00:22<00:10,  3.86it/s]

skip image images/model_c000001_0000003.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  66%|██████▌   | 76/115 [00:22<00:10,  3.83it/s]

skip image images/kenzonaplane-20260216-0055.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  67%|██████▋   | 77/115 [00:22<00:10,  3.71it/s]

skip image images/kenzonaplane-20260216-0060.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  68%|██████▊   | 78/115 [00:23<00:10,  3.67it/s]

skip image images/kenzonaplane-20260216-0040.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  69%|██████▊   | 79/115 [00:23<00:09,  3.82it/s]

skip image images/model_c000002_0000018.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  70%|██████▉   | 80/115 [00:23<00:09,  3.83it/s]

skip image images/kenzonaplane-20260216-0049.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  70%|███████   | 81/115 [00:23<00:09,  3.72it/s]

skip image images/kenzonaplane-20260216-0069.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  71%|███████▏  | 82/115 [00:24<00:08,  3.94it/s]

skip image images/cookie_c000004_0000044.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  72%|███████▏  | 83/115 [00:24<00:07,  4.01it/s]

skip image images/client_c000002_0000028.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  73%|███████▎  | 84/115 [00:24<00:07,  4.14it/s]

skip image images/blockheart_c000001_0000048.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  74%|███████▍  | 85/115 [00:24<00:07,  4.01it/s]

skip image images/kenzonaplane-20260216-0021.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  75%|███████▍  | 86/115 [00:24<00:06,  4.16it/s]

skip image images/cookie_c000001_0000001.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  76%|███████▌  | 87/115 [00:25<00:07,  3.98it/s]

skip image images/kenzonaplane-20260216-0024.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  77%|███████▋  | 88/115 [00:25<00:07,  3.78it/s]

skip image images/kenzonaplane-20260216-0023.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  77%|███████▋  | 89/115 [00:25<00:06,  3.96it/s]

skip image images/model_c000004_0000034.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  78%|███████▊  | 90/115 [00:26<00:06,  3.84it/s]

skip image images/kenzonaplane-20260216-0065.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  79%|███████▉  | 91/115 [00:26<00:06,  3.48it/s]

skip image images/cookie_c000004_0000042.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  80%|████████  | 92/115 [00:26<00:07,  3.25it/s]

skip image images/model_c000004_0000037.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  81%|████████  | 93/115 [00:27<00:07,  3.09it/s]

skip image images/model_c000001_0000046.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  82%|████████▏ | 94/115 [00:27<00:07,  2.79it/s]

skip image images/kenzonaplane-20260216-0020.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  83%|████████▎ | 95/115 [00:28<00:07,  2.58it/s]

skip image images/kenzonaplane-20260216-0038.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  83%|████████▎ | 96/115 [00:28<00:07,  2.61it/s]

skip image images/cookie_c000002_0000009.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  84%|████████▍ | 97/115 [00:28<00:07,  2.44it/s]

skip image images/kenzonaplane-20260216-0070.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  85%|████████▌ | 98/115 [00:29<00:06,  2.56it/s]

skip image images/model_c000004_0000035.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  86%|████████▌ | 99/115 [00:29<00:05,  2.74it/s]

skip image images/kenzonaplane-20260216-0005.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  87%|████████▋ | 100/115 [00:29<00:04,  3.10it/s]

skip image images/client_c000003_0000030.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  88%|████████▊ | 101/115 [00:29<00:04,  3.45it/s]

skip image images/model_c000002_0000007.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  89%|████████▊ | 102/115 [00:30<00:03,  3.53it/s]

skip image images/kenzonaplane-20260216-0036.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  90%|████████▉ | 103/115 [00:30<00:03,  3.78it/s]

skip image images/brian_c000001_0000045.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  90%|█████████ | 104/115 [00:30<00:02,  3.69it/s]

skip image images/kenzonaplane-20260216-0027.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  91%|█████████▏| 105/115 [00:30<00:02,  3.89it/s]

skip image images/model_c000002_0000006.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  92%|█████████▏| 106/115 [00:31<00:02,  3.79it/s]

skip image images/kenzonaplane-20260216-0067.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  93%|█████████▎| 107/115 [00:31<00:02,  3.78it/s]

skip image images/kenzonaplane-20260216-0025.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  94%|█████████▍| 108/115 [00:31<00:01,  3.70it/s]

skip image images/kenzonaplane-20260216-0068.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  95%|█████████▍| 109/115 [00:32<00:01,  3.66it/s]

skip image images/kenzonaplane-20260216-0031.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  96%|█████████▌| 110/115 [00:32<00:01,  3.88it/s]

skip image images/client_c000003_0000029.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  97%|█████████▋| 111/115 [00:32<00:00,  4.05it/s]

skip image images/client_c000002_0000017.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  97%|█████████▋| 112/115 [00:32<00:00,  3.87it/s]

skip image images/kenzonaplane-20260216-0057.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  98%|█████████▊| 113/115 [00:32<00:00,  4.05it/s]

skip image images/client_c000002_0000014.png 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image:  99%|█████████▉| 114/115 [00:33<00:00,  3.96it/s]

skip image images/kenzonaplane-20260216-0041.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher image: 100%|██████████| 115/115 [00:33<00:00,  3.43it/s]

skip image images/kenzonaplane-20260216-0033.jpg 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:   2%|▏         | 1/50 [00:00<00:12,  3.96it/s]

skip video video/cookie_c000003_0000024.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:   4%|▍         | 2/50 [00:00<00:11,  4.25it/s]

skip video video/model_c000002_0000006.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:   6%|▌         | 3/50 [00:00<00:10,  4.32it/s]

skip video video/model_c000003_0000033.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:   8%|▊         | 4/50 [00:00<00:10,  4.38it/s]

skip video video/model_c000001_0000003.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  10%|█         | 5/50 [00:01<00:10,  4.27it/s]

skip video video/cookie_c000003_0000025.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  12%|█▏        | 6/50 [00:01<00:10,  4.32it/s]

skip video video/client_c000002_0000028.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  14%|█▍        | 7/50 [00:01<00:09,  4.33it/s]

skip video video/client_c000002_0000015.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  16%|█▌        | 8/50 [00:01<00:09,  4.36it/s]

skip video video/model_c000002_0000007.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  18%|█▊        | 9/50 [00:02<00:09,  4.29it/s]

skip video video/model_c000002_0000004.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  20%|██        | 10/50 [00:02<00:09,  4.26it/s]

skip video video/model_c000001_0000000.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  22%|██▏       | 11/50 [00:02<00:08,  4.33it/s]

skip video video/model_c000003_0000021.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  24%|██▍       | 12/50 [00:02<00:08,  4.35it/s]

skip video video/cookie_c000003_0000026.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  26%|██▌       | 13/50 [00:03<00:08,  4.37it/s]

skip video video/client_c000002_0000017.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  28%|██▊       | 14/50 [00:03<00:08,  4.27it/s]

skip video video/model_c000001_0000046.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  30%|███       | 15/50 [00:03<00:08,  4.29it/s]

skip video video/cookie_c000004_0000040.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  32%|███▏      | 16/50 [00:03<00:07,  4.33it/s]

skip video video/cookie_c000003_0000027.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  34%|███▍      | 17/50 [00:03<00:07,  4.35it/s]

skip video video/cookie_c000004_0000041.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  36%|███▌      | 18/50 [00:04<00:07,  4.33it/s]

skip video video/client_c000003_0000032.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  38%|███▊      | 19/50 [00:04<00:07,  4.28it/s]

skip video video/model_c000003_0000022.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  40%|████      | 20/50 [00:04<00:07,  4.28it/s]

skip video video/client_c000003_0000031.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  42%|████▏     | 21/50 [00:04<00:06,  4.34it/s]

skip video video/cookie_c000001_0000008.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  44%|████▍     | 22/50 [00:05<00:06,  4.37it/s]

skip video video/cookie_c000004_0000042.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  46%|████▌     | 23/50 [00:05<00:06,  4.29it/s]

skip video video/client_c000002_0000014.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  48%|████▊     | 24/50 [00:05<00:06,  4.32it/s]

skip video video/client_c000003_0000030.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  50%|█████     | 25/50 [00:05<00:06,  3.87it/s]

skip video video/blockheart_c000001_0000048.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  52%|█████▏    | 26/50 [00:06<00:06,  3.48it/s]

skip video video/client_c000001_0000002.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  54%|█████▍    | 27/50 [00:06<00:07,  3.22it/s]

skip video video/cookie_c000002_0000023.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  56%|█████▌    | 28/50 [00:06<00:07,  3.07it/s]

skip video video/model_c000003_0000019.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  58%|█████▊    | 29/50 [00:07<00:07,  2.95it/s]

skip video video/cookie_c000001_0000001.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  60%|██████    | 30/50 [00:07<00:06,  2.87it/s]

skip video video/model_c000004_0000036.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  62%|██████▏   | 31/50 [00:08<00:06,  2.84it/s]

skip video video/cookie_c000004_0000039.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  64%|██████▍   | 32/50 [00:08<00:06,  2.81it/s]

skip video video/cookie_c000002_0000009.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  66%|██████▌   | 33/50 [00:08<00:05,  2.92it/s]

skip video video/brian_c000001_0000045.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  68%|██████▊   | 34/50 [00:08<00:04,  3.25it/s]

skip video video/cookie_c000002_0000011.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  70%|███████   | 35/50 [00:09<00:04,  3.52it/s]

skip video video/model_c000003_0000020.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  72%|███████▏  | 36/50 [00:09<00:03,  3.75it/s]

skip video video/blockheart_c000001_0000047.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  74%|███████▍  | 37/50 [00:09<00:03,  3.86it/s]

skip video video/model_c000004_0000034.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  76%|███████▌  | 38/50 [00:09<00:02,  4.02it/s]

skip video video/cookie_c000002_0000010.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  78%|███████▊  | 39/50 [00:10<00:02,  4.10it/s]

skip video video/cookie_c000003_0000038.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  80%|████████  | 40/50 [00:10<00:02,  4.17it/s]

skip video video/model_c000004_0000037.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  82%|████████▏ | 41/50 [00:10<00:02,  4.27it/s]

skip video video/cookie_c000004_0000043.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  84%|████████▍ | 42/50 [00:10<00:01,  4.27it/s]

skip video video/client_c000003_0000029.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  86%|████████▌ | 43/50 [00:11<00:01,  4.27it/s]

skip video video/cookie_c000002_0000012.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  88%|████████▊ | 44/50 [00:12<00:03,  1.90it/s]

skip video video/AQPkSX-nmiIa2uccaLlNS8tnTWhGJ5y9zCGilF11YDrVwqV7n45u8N6tR9XYP8Mnjbu046eOK5txoPRj3nLUbad0NTxU6axQDc41fQM.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  90%|█████████ | 45/50 [00:12<00:02,  2.29it/s]

skip video video/model_c000004_0000035.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  92%|█████████▏| 46/50 [00:12<00:01,  2.65it/s]

skip video video/model_c000002_0000005.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  94%|█████████▍| 47/50 [00:12<00:00,  3.02it/s]

skip video video/client_c000002_0000016.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  96%|█████████▌| 48/50 [00:13<00:00,  3.32it/s]

skip video video/client_c000001_0000013.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video:  98%|█████████▊| 49/50 [00:13<00:00,  3.59it/s]

skip video video/model_c000002_0000018.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher video: 100%|██████████| 50/50 [00:13<00:00,  3.67it/s]

skip video video/cookie_c000004_0000044.mp4 'BaseModelOutputWithPooling' object has no attribute 'norm'

teacher audio: 100%|██████████| 49/49 [00:17<00:00,  2.87it/s]

✅ Teacher cache: (98, 7) saved to /content/hf_teacher_cache.parquet

,rel,modality,valence,arousal,calm,trust,w2v_emb
0,text/client_c000002_0000017.txt,text,0.511199,0.150625,0.849375,0.507465,NaN
1,text/model_c000002_0000004.txt,text,0.508652,0.198813,0.801187,0.505504,NaN
2,text/blockheart_c000001_0000048.txt,text,0.518708,0.059151,0.940849,0.514630,NaN
3,text/model_c000004_0000036.txt,text,0.513505,0.057568,0.942432,0.508758,NaN
4,text/model_c000004_0000034.txt,text,0.510257,0.167567,0.832433,0.506945,NaN

In [16]:
#@title 6) Train student head + export TorchScript
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

merged = df.merge(pd.read_parquet(CACHE_PATH), on=["rel","modality"], how="inner")

# expand embeddings
def expand_vec(colname, prefix):
    if colname not in merged.columns: return
    vecs = merged[colname].dropna()
    if len(vecs)==0: return
    dim = len(vecs.iloc[0])

    # The original error was because fillna was called with a list, which is not supported for Series.
    # Instead, we iterate and conditionally replace non-list items (including NaN) with zero vectors.
    arr_list = []
    for val in merged[colname]:
        if isinstance(val, list):
            arr_list.append(val)
        else:
            arr_list.append([0.0]*dim)

    arr = np.vstack(arr_list)

    for i in range(dim):
        merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
    merged.drop(columns=[colname], inplace=True)

expand_vec("clip_emb","clip_")
expand_vec("w2v_emb","w2v_")

TARGETS=["valence","arousal","calm","trust"]
ignore=set(["path","rel","modality"]+TARGETS)
numeric_cols=[c for c in merged.columns if c not in ignore and pd.api.types.is_numeric_dtype(merged[c])]

X = merged[numeric_cols].astype(np.float32).values
Y = merged[TARGETS].astype(np.float32).values

mu=X.mean(axis=0, keepdims=True)
sd=X.std(axis=0, keepdims=True)+1e-6
Xn=(X-mu)/sd

class TableDS(Dataset):
    def __init__(self, X, Y):
        self.X=torch.tensor(X, dtype=torch.float32)
        self.Y=torch.tensor(Y, dtype=torch.float32)
    def __len__(self): return self.X.shape[0]
    def __getitem__(self,i): return self.X[i], self.Y[i]

ds=TableDS(Xn,Y)
dl=DataLoader(ds,batch_size=64,shuffle=True)

student = nn.Sequential(
    nn.Linear(Xn.shape[1],256), nn.Tanh(),
    nn.Linear(256,128), nn.Tanh(),
    nn.Linear(128,4), nn.Sigmoid()
)

dev="cuda" if torch.cuda.is_available() else "cpu"
student.to(dev)
opt=torch.optim.Adam(student.parameters(), lr=1e-3)
loss_fn=nn.MSELoss()

student.train()
for epoch in range(12000):
    total=0.0
    for xb,yb in dl:
        xb,yb=xb.to(dev), yb.to(dev)
        pred=student(xb)
        loss=loss_fn(pred,yb)
        opt.zero_grad(); loss.backward(); opt.step()
        total += loss.item()*xb.size(0)
    print(f"epoch {epoch:02d} mse {total/len(ds):.6f}")

student_cpu = student.to("cpu").eval()
example=torch.zeros(1, Xn.shape[1])
ts=torch.jit.trace(student_cpu, example)
student_ts_path="/content/student_distilled_heads_hf.torchscript.pt"
ts.save(student_ts_path)

norm_path="/content/student_norm_hf.json"
with open(norm_path,"w",encoding="utf-8") as f:
    json.dump({"numeric_cols":numeric_cols,"mu":mu.flatten().tolist(),"sd":sd.flatten().tolist()}, f)

print("✅ Saved:", student_ts_path)
print("✅ Norm :", norm_path)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)
 [py.warnings]
WARNING:py.warnings:/tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged[f"{prefix}{i}"] = arr[:, i].astype(np.float32)

WARNING    /tmp/ipython-input-749115814.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

Streaming output truncated to the last 5000 lines.
epoch 7002 mse 0.000568
epoch 7003 mse 0.000567
epoch 7004 mse 0.000567
epoch 7005 mse 0.000569
epoch 7006 mse 0.000574
epoch 7007 mse 0.000566
epoch 7008 mse 0.000570
epoch 7009 mse 0.000588
epoch 7010 mse 0.000601
epoch 7011 mse 0.000579
epoch 7012 mse 0.000572
epoch 7013 mse 0.000615
epoch 7014 mse 0.000572
epoch 7015 mse 0.000578
epoch 7016 mse 0.000575
epoch 7017 mse 0.000565
epoch 7018 mse 0.000568
epoch 7019 mse 0.000563
epoch 7020 mse 0.000562
epoch 7021 mse 0.000565
epoch 7022 mse 0.000564
epoch 7023 mse 0.000587
epoch 7024 mse 0.000583
epoch 7025 mse 0.000568
epoch 7026 mse 0.000586
epoch 7027 mse 0.000591
epoch 7028 mse 0.000593
epoch 7029 mse 0.000576
epoch 7030 mse 0.000591
epoch 7031 mse 0.000591
epoch 7032 mse 0.000581
epoch 7033 mse 0.000559
epoch 7034 mse 0.000588
epoch 7035 mse 0.000582
epoch 7036 mse 0.000577
epoch 7037 mse 0.000583
epoch 7038 mse 0.000575
epoch 7039 mse 0.000585
epoch 7040 mse 0.000573
epoch 7041 mse 0.000575
epoch 7042 mse 0.000563
epoch 7043 mse 0.000563
epoch 7044 mse 0.000567
epoch 7045 mse 0.000562
epoch 7046 mse 0.000565
epoch 7047 mse 0.000572
epoch 7048 mse 0.000564
epoch 7049 mse 0.000575
epoch 7050 mse 0.000586
epoch 7051 mse 0.000568
epoch 7052 mse 0.000564
epoch 7053 mse 0.000569
epoch 7054 mse 0.000570
epoch 7055 mse 0.000558
epoch 7056 mse 0.000571
epoch 7057 mse 0.000583
epoch 7058 mse 0.000575
epoch 7059 mse 0.000564
epoch 7060 mse 0.000563
epoch 7061 mse 0.000586
epoch 7062 mse 0.000578
epoch 7063 mse 0.000570
epoch 7064 mse 0.000593
epoch 7065 mse 0.000585
epoch 7066 mse 0.000570
epoch 7067 mse 0.000571
epoch 7068 mse 0.000587
epoch 7069 mse 0.000575
epoch 7070 mse 0.000582
epoch 7071 mse 0.000563
epoch 7072 mse 0.000576
epoch 7073 mse 0.000568
epoch 7074 mse 0.000563
epoch 7075 mse 0.000584
epoch 7076 mse 0.000564
epoch 7077 mse 0.000569
epoch 7078 mse 0.000564
epoch 7079 mse 0.000567
epoch 7080 mse 0.000561
epoch 7081 mse 0.000567
epoch 7082 mse 0.000570
epoch 7083 mse 0.000568
epoch 7084 mse 0.000562
epoch 7085 mse 0.000576
epoch 7086 mse 0.000563
epoch 7087 mse 0.000569
epoch 7088 mse 0.000571
epoch 7089 mse 0.000565
epoch 7090 mse 0.000569
epoch 7091 mse 0.000564
epoch 7092 mse 0.000562
epoch 7093 mse 0.000564
epoch 7094 mse 0.000562
epoch 7095 mse 0.000575
epoch 7096 mse 0.000576
epoch 7097 mse 0.000587
epoch 7098 mse 0.000574
epoch 7099 mse 0.000564
epoch 7100 mse 0.000596
epoch 7101 mse 0.000590
epoch 7102 mse 0.000575
epoch 7103 mse 0.000578
epoch 7104 mse 0.000590
epoch 7105 mse 0.000578
epoch 7106 mse 0.000577
epoch 7107 mse 0.000584
epoch 7108 mse 0.000589
epoch 7109 mse 0.000569
epoch 7110 mse 0.000564
epoch 7111 mse 0.000560
epoch 7112 mse 0.000585
epoch 7113 mse 0.000571
epoch 7114 mse 0.000569
epoch 7115 mse 0.000580
epoch 7116 mse 0.000574
epoch 7117 mse 0.000572
epoch 7118 mse 0.000566
epoch 7119 mse 0.000572
epoch 7120 mse 0.000569
epoch 7121 mse 0.000563
epoch 7122 mse 0.000567
epoch 7123 mse 0.000567
epoch 7124 mse 0.000562
epoch 7125 mse 0.000569
epoch 7126 mse 0.000573
epoch 7127 mse 0.000571
epoch 7128 mse 0.000590
epoch 7129 mse 0.000564
epoch 7130 mse 0.000564
epoch 7131 mse 0.000563
epoch 7132 mse 0.000568
epoch 7133 mse 0.000561
epoch 7134 mse 0.000569
epoch 7135 mse 0.000574
epoch 7136 mse 0.000563
epoch 7137 mse 0.000571
epoch 7138 mse 0.000568
epoch 7139 mse 0.000568
epoch 7140 mse 0.000559
epoch 7141 mse 0.000572
epoch 7142 mse 0.000581
epoch 7143 mse 0.000570
epoch 7144 mse 0.000564
epoch 7145 mse 0.000570
epoch 7146 mse 0.000576
epoch 7147 mse 0.000562
epoch 7148 mse 0.000570
epoch 7149 mse 0.000564
epoch 7150 mse 0.000574
epoch 7151 mse 0.000568
epoch 7152 mse 0.000567
epoch 7153 mse 0.000563
epoch 7154 mse 0.000579
epoch 7155 mse 0.000563
epoch 7156 mse 0.000574
epoch 7157 mse 0.000576
epoch 7158 mse 0.000566
epoch 7159 mse 0.000575
epoch 7160 mse 0.000590
epoch 7161 mse 0.000581
epoch 7162 mse 0.000564
epoch 7163 mse 0.000588
epoch 7164 mse 0.000579
epoch 7165 mse 0.000577
epoch 7166 mse 0.000582
epoch 7167 mse 0.000579
epoch 7168 mse 0.000579
epoch 7169 mse 0.000571
epoch 7170 mse 0.000585
epoch 7171 mse 0.000578
epoch 7172 mse 0.000573
epoch 7173 mse 0.000564
epoch 7174 mse 0.000563
epoch 7175 mse 0.000573
epoch 7176 mse 0.000571
epoch 7177 mse 0.000563
epoch 7178 mse 0.000572
epoch 7179 mse 0.000571
epoch 7180 mse 0.000563
epoch 7181 mse 0.000570
epoch 7182 mse 0.000561
epoch 7183 mse 0.000571
epoch 7184 mse 0.000566
epoch 7185 mse 0.000566
epoch 7186 mse 0.000562
epoch 7187 mse 0.000574
epoch 7188 mse 0.000567
epoch 7189 mse 0.000572
epoch 7190 mse 0.000572
epoch 7191 mse 0.000566
epoch 7192 mse 0.000571
epoch 7193 mse 0.000573
epoch 7194 mse 0.000590
epoch 7195 mse 0.000575
epoch 7196 mse 0.000589
epoch 7197 mse 0.000598
epoch 7198 mse 0.000572
epoch 7199 mse 0.000571
epoch 7200 mse 0.000567
epoch 7201 mse 0.000597
epoch 7202 mse 0.000590
epoch 7203 mse 0.000578
epoch 7204 mse 0.000582
epoch 7205 mse 0.000604
epoch 7206 mse 0.000575
epoch 7207 mse 0.000568
epoch 7208 mse 0.000568
epoch 7209 mse 0.000562
epoch 7210 mse 0.000566
epoch 7211 mse 0.000566
epoch 7212 mse 0.000564
epoch 7213 mse 0.000570
epoch 7214 mse 0.000560
epoch 7215 mse 0.000564
epoch 7216 mse 0.000573
epoch 7217 mse 0.000587
epoch 7218 mse 0.000583
epoch 7219 mse 0.000568
epoch 7220 mse 0.000590
epoch 7221 mse 0.000597
epoch 7222 mse 0.000582
epoch 7223 mse 0.000596
epoch 7224 mse 0.000573
epoch 7225 mse 0.000588
epoch 7226 mse 0.000568
epoch 7227 mse 0.000569
epoch 7228 mse 0.000569
epoch 7229 mse 0.000588
epoch 7230 mse 0.000587
epoch 7231 mse 0.000565
epoch 7232 mse 0.000596
epoch 7233 mse 0.000570
epoch 7234 mse 0.000569
epoch 7235 mse 0.000567
epoch 7236 mse 0.000563
epoch 7237 mse 0.000567
epoch 7238 mse 0.000578
epoch 7239 mse 0.000579
epoch 7240 mse 0.000566
epoch 7241 mse 0.000572
epoch 7242 mse 0.000569
epoch 7243 mse 0.000563
epoch 7244 mse 0.000567
epoch 7245 mse 0.000575
epoch 7246 mse 0.000567
epoch 7247 mse 0.000561
epoch 7248 mse 0.000563
epoch 7249 mse 0.000570
epoch 7250 mse 0.000568
epoch 7251 mse 0.000569
epoch 7252 mse 0.000566
epoch 7253 mse 0.000565
epoch 7254 mse 0.000561
epoch 7255 mse 0.000562
epoch 7256 mse 0.000562
epoch 7257 mse 0.000568
epoch 7258 mse 0.000569
epoch 7259 mse 0.000568
epoch 7260 mse 0.000565
epoch 7261 mse 0.000560
epoch 7262 mse 0.000570
epoch 7263 mse 0.000591
epoch 7264 mse 0.000579
epoch 7265 mse 0.000579
epoch 7266 mse 0.000569
epoch 7267 mse 0.000586
epoch 7268 mse 0.000592
epoch 7269 mse 0.000567
epoch 7270 mse 0.000582
epoch 7271 mse 0.000591
epoch 7272 mse 0.000571
epoch 7273 mse 0.000587
epoch 7274 mse 0.000577
epoch 7275 mse 0.000605
epoch 7276 mse 0.000569
epoch 7277 mse 0.000588
epoch 7278 mse 0.000608
epoch 7279 mse 0.000579
epoch 7280 mse 0.000573
epoch 7281 mse 0.000576
epoch 7282 mse 0.000579
epoch 7283 mse 0.000571
epoch 7284 mse 0.000566
epoch 7285 mse 0.000572
epoch 7286 mse 0.000578
epoch 7287 mse 0.000579
epoch 7288 mse 0.000564
epoch 7289 mse 0.000572
epoch 7290 mse 0.000587
epoch 7291 mse 0.000562
epoch 7292 mse 0.000566
epoch 7293 mse 0.000580
epoch 7294 mse 0.000579
epoch 7295 mse 0.000569
epoch 7296 mse 0.000578
epoch 7297 mse 0.000563
epoch 7298 mse 0.000574
epoch 7299 mse 0.000570
epoch 7300 mse 0.000575
epoch 7301 mse 0.000562
epoch 7302 mse 0.000572
epoch 7303 mse 0.000574
epoch 7304 mse 0.000564
epoch 7305 mse 0.000565
epoch 7306 mse 0.000570
epoch 7307 mse 0.000562
epoch 7308 mse 0.000564
epoch 7309 mse 0.000570
epoch 7310 mse 0.000565
epoch 7311 mse 0.000565
epoch 7312 mse 0.000568
epoch 7313 mse 0.000564
epoch 7314 mse 0.000570
epoch 7315 mse 0.000578
epoch 7316 mse 0.000568
epoch 7317 mse 0.000573
epoch 7318 mse 0.000560
epoch 7319 mse 0.000583
epoch 7320 mse 0.000582
epoch 7321 mse 0.000581
epoch 7322 mse 0.000570
epoch 7323 mse 0.000574
epoch 7324 mse 0.000575
epoch 7325 mse 0.000569
epoch 7326 mse 0.000566
epoch 7327 mse 0.000562
epoch 7328 mse 0.000564
epoch 7329 mse 0.000567
epoch 7330 mse 0.000569
epoch 7331 mse 0.000570
epoch 7332 mse 0.000584
epoch 7333 mse 0.000574
epoch 7334 mse 0.000563
epoch 7335 mse 0.000574
epoch 7336 mse 0.000561
epoch 7337 mse 0.000563
epoch 7338 mse 0.000567
epoch 7339 mse 0.000560
epoch 7340 mse 0.000567
epoch 7341 mse 0.000563
epoch 7342 mse 0.000568
epoch 7343 mse 0.000575
epoch 7344 mse 0.000568
epoch 7345 mse 0.000567
epoch 7346 mse 0.000568
epoch 7347 mse 0.000570
epoch 7348 mse 0.000574
epoch 7349 mse 0.000574
epoch 7350 mse 0.000565
epoch 7351 mse 0.000563
epoch 7352 mse 0.000576
epoch 7353 mse 0.000590
epoch 7354 mse 0.000578
epoch 7355 mse 0.000573
epoch 7356 mse 0.000592
epoch 7357 mse 0.000595
epoch 7358 mse 0.000607
epoch 7359 mse 0.000579
epoch 7360 mse 0.000606
epoch 7361 mse 0.000603
epoch 7362 mse 0.000585
epoch 7363 mse 0.000564
epoch 7364 mse 0.000595
epoch 7365 mse 0.000588
epoch 7366 mse 0.000568
epoch 7367 mse 0.000581
epoch 7368 mse 0.000594
epoch 7369 mse 0.000578
epoch 7370 mse 0.000571
epoch 7371 mse 0.000608
epoch 7372 mse 0.000576
epoch 7373 mse 0.000576
epoch 7374 mse 0.000585
epoch 7375 mse 0.000566
epoch 7376 mse 0.000567
epoch 7377 mse 0.000567
epoch 7378 mse 0.000571
epoch 7379 mse 0.000564
epoch 7380 mse 0.000573
epoch 7381 mse 0.000565
epoch 7382 mse 0.000569
epoch 7383 mse 0.000573
epoch 7384 mse 0.000567
epoch 7385 mse 0.000567
epoch 7386 mse 0.000563
epoch 7387 mse 0.000564
epoch 7388 mse 0.000564
epoch 7389 mse 0.000561
epoch 7390 mse 0.000562
epoch 7391 mse 0.000567
epoch 7392 mse 0.000568
epoch 7393 mse 0.000561
epoch 7394 mse 0.000568
epoch 7395 mse 0.000571
epoch 7396 mse 0.000569
epoch 7397 mse 0.000566
epoch 7398 mse 0.000562
epoch 7399 mse 0.000572
epoch 7400 mse 0.000577
epoch 7401 mse 0.000570
epoch 7402 mse 0.000564
epoch 7403 mse 0.000564
epoch 7404 mse 0.000574
epoch 7405 mse 0.000570
epoch 7406 mse 0.000573
epoch 7407 mse 0.000589
epoch 7408 mse 0.000562
epoch 7409 mse 0.000574
epoch 7410 mse 0.000575
epoch 7411 mse 0.000573
epoch 7412 mse 0.000562
epoch 7413 mse 0.000573
epoch 7414 mse 0.000574
epoch 7415 mse 0.000567
epoch 7416 mse 0.000574
epoch 7417 mse 0.000575
epoch 7418 mse 0.000566
epoch 7419 mse 0.000577
epoch 7420 mse 0.000574
epoch 7421 mse 0.000566
epoch 7422 mse 0.000571
epoch 7423 mse 0.000574
epoch 7424 mse 0.000564
epoch 7425 mse 0.000566
epoch 7426 mse 0.000588
epoch 7427 mse 0.000578
epoch 7428 mse 0.000577
epoch 7429 mse 0.000590
epoch 7430 mse 0.000579
epoch 7431 mse 0.000595
epoch 7432 mse 0.000587
epoch 7433 mse 0.000580
epoch 7434 mse 0.000564
epoch 7435 mse 0.000575
epoch 7436 mse 0.000571
epoch 7437 mse 0.000565
epoch 7438 mse 0.000573
epoch 7439 mse 0.000588
epoch 7440 mse 0.000570
epoch 7441 mse 0.000582
epoch 7442 mse 0.000603
epoch 7443 mse 0.000583
epoch 7444 mse 0.000576
epoch 7445 mse 0.000591
epoch 7446 mse 0.000612
epoch 7447 mse 0.000582
epoch 7448 mse 0.000584
epoch 7449 mse 0.000590
epoch 7450 mse 0.000580
epoch 7451 mse 0.000567
epoch 7452 mse 0.000571
epoch 7453 mse 0.000575
epoch 7454 mse 0.000566
epoch 7455 mse 0.000570
epoch 7456 mse 0.000570
epoch 7457 mse 0.000562
epoch 7458 mse 0.000571
epoch 7459 mse 0.000560
epoch 7460 mse 0.000566
epoch 7461 mse 0.000565
epoch 7462 mse 0.000567
epoch 7463 mse 0.000563
epoch 7464 mse 0.000574
epoch 7465 mse 0.000578
epoch 7466 mse 0.000590
epoch 7467 mse 0.000561
epoch 7468 mse 0.000590
epoch 7469 mse 0.000592
epoch 7470 mse 0.000570
epoch 7471 mse 0.000571
epoch 7472 mse 0.000561
epoch 7473 mse 0.000568
epoch 7474 mse 0.000566
epoch 7475 mse 0.000564
epoch 7476 mse 0.000564
epoch 7477 mse 0.000578
epoch 7478 mse 0.000560
epoch 7479 mse 0.000567
epoch 7480 mse 0.000568
epoch 7481 mse 0.000565
epoch 7482 mse 0.000568
epoch 7483 mse 0.000572
epoch 7484 mse 0.000562
epoch 7485 mse 0.000566
epoch 7486 mse 0.000573
epoch 7487 mse 0.000562
epoch 7488 mse 0.000561
epoch 7489 mse 0.000567
epoch 7490 mse 0.000571
epoch 7491 mse 0.000574
epoch 7492 mse 0.000562
epoch 7493 mse 0.000585
epoch 7494 mse 0.000594
epoch 7495 mse 0.000587
epoch 7496 mse 0.000582
epoch 7497 mse 0.000578
epoch 7498 mse 0.000578
epoch 7499 mse 0.000570
epoch 7500 mse 0.000562
epoch 7501 mse 0.000572
epoch 7502 mse 0.000570
epoch 7503 mse 0.000564
epoch 7504 mse 0.000569
epoch 7505 mse 0.000563
epoch 7506 mse 0.000566
epoch 7507 mse 0.000562
epoch 7508 mse 0.000564
epoch 7509 mse 0.000578
epoch 7510 mse 0.000573
epoch 7511 mse 0.000563
epoch 7512 mse 0.000575
epoch 7513 mse 0.000591
epoch 7514 mse 0.000568
epoch 7515 mse 0.000564
epoch 7516 mse 0.000580
epoch 7517 mse 0.000561
epoch 7518 mse 0.000573
epoch 7519 mse 0.000581
epoch 7520 mse 0.000566
epoch 7521 mse 0.000567
epoch 7522 mse 0.000604
epoch 7523 mse 0.000586
epoch 7524 mse 0.000573
epoch 7525 mse 0.000583
epoch 7526 mse 0.000578
epoch 7527 mse 0.000569
epoch 7528 mse 0.000572
epoch 7529 mse 0.000568
epoch 7530 mse 0.000583
epoch 7531 mse 0.000578
epoch 7532 mse 0.000586
epoch 7533 mse 0.000572
epoch 7534 mse 0.000599
epoch 7535 mse 0.000592
epoch 7536 mse 0.000577
epoch 7537 mse 0.000583
epoch 7538 mse 0.000573
epoch 7539 mse 0.000575
epoch 7540 mse 0.000575
epoch 7541 mse 0.000568
epoch 7542 mse 0.000562
epoch 7543 mse 0.000566
epoch 7544 mse 0.000568
epoch 7545 mse 0.000571
epoch 7546 mse 0.000572
epoch 7547 mse 0.000561
epoch 7548 mse 0.000562
epoch 7549 mse 0.000567
epoch 7550 mse 0.000566
epoch 7551 mse 0.000563
epoch 7552 mse 0.000562
epoch 7553 mse 0.000571
epoch 7554 mse 0.000578
epoch 7555 mse 0.000600
epoch 7556 mse 0.000577
epoch 7557 mse 0.000566
epoch 7558 mse 0.000575
epoch 7559 mse 0.000571
epoch 7560 mse 0.000566
epoch 7561 mse 0.000577
epoch 7562 mse 0.000571
epoch 7563 mse 0.000567
epoch 7564 mse 0.000584
epoch 7565 mse 0.000584
epoch 7566 mse 0.000574
epoch 7567 mse 0.000577
epoch 7568 mse 0.000584
epoch 7569 mse 0.000579
epoch 7570 mse 0.000574
epoch 7571 mse 0.000581
epoch 7572 mse 0.000571
epoch 7573 mse 0.000564
epoch 7574 mse 0.000561
epoch 7575 mse 0.000561
epoch 7576 mse 0.000568
epoch 7577 mse 0.000562
epoch 7578 mse 0.000569
epoch 7579 mse 0.000568
epoch 7580 mse 0.000576
epoch 7581 mse 0.000581
epoch 7582 mse 0.000565
epoch 7583 mse 0.000566
epoch 7584 mse 0.000585
epoch 7585 mse 0.000561
epoch 7586 mse 0.000563
epoch 7587 mse 0.000568
epoch 7588 mse 0.000571
epoch 7589 mse 0.000570
epoch 7590 mse 0.000566
epoch 7591 mse 0.000565
epoch 7592 mse 0.000567
epoch 7593 mse 0.000569
epoch 7594 mse 0.000569
epoch 7595 mse 0.000567
epoch 7596 mse 0.000593
epoch 7597 mse 0.000590
epoch 7598 mse 0.000571
epoch 7599 mse 0.000597
epoch 7600 mse 0.000574
epoch 7601 mse 0.000566
epoch 7602 mse 0.000572
epoch 7603 mse 0.000581
epoch 7604 mse 0.000569
epoch 7605 mse 0.000571
epoch 7606 mse 0.000571
epoch 7607 mse 0.000572
epoch 7608 mse 0.000571
epoch 7609 mse 0.000573
epoch 7610 mse 0.000575
epoch 7611 mse 0.000561
epoch 7612 mse 0.000574
epoch 7613 mse 0.000573
epoch 7614 mse 0.000564
epoch 7615 mse 0.000578
epoch 7616 mse 0.000563
epoch 7617 mse 0.000561
epoch 7618 mse 0.000561
epoch 7619 mse 0.000560
epoch 7620 mse 0.000567
epoch 7621 mse 0.000565
epoch 7622 mse 0.000565
epoch 7623 mse 0.000570
epoch 7624 mse 0.000567
epoch 7625 mse 0.000557
epoch 7626 mse 0.000569
epoch 7627 mse 0.000588
epoch 7628 mse 0.000570
epoch 7629 mse 0.000571
epoch 7630 mse 0.000608
epoch 7631 mse 0.000599
epoch 7632 mse 0.000577
epoch 7633 mse 0.000589
epoch 7634 mse 0.000617
epoch 7635 mse 0.000582
epoch 7636 mse 0.000570
epoch 7637 mse 0.000564
epoch 7638 mse 0.000569
epoch 7639 mse 0.000566
epoch 7640 mse 0.000568
epoch 7641 mse 0.000566
epoch 7642 mse 0.000586
epoch 7643 mse 0.000580
epoch 7644 mse 0.000577
epoch 7645 mse 0.000594
epoch 7646 mse 0.000585
epoch 7647 mse 0.000612
epoch 7648 mse 0.000603
epoch 7649 mse 0.000591
epoch 7650 mse 0.000597
epoch 7651 mse 0.000573
epoch 7652 mse 0.000571
epoch 7653 mse 0.000571
epoch 7654 mse 0.000570
epoch 7655 mse 0.000566
epoch 7656 mse 0.000564
epoch 7657 mse 0.000565
epoch 7658 mse 0.000566
epoch 7659 mse 0.000562
epoch 7660 mse 0.000566
epoch 7661 mse 0.000572
epoch 7662 mse 0.000572
epoch 7663 mse 0.000573
epoch 7664 mse 0.000569
epoch 7665 mse 0.000593
epoch 7666 mse 0.000592
epoch 7667 mse 0.000569
epoch 7668 mse 0.000582
epoch 7669 mse 0.000582
epoch 7670 mse 0.000565
epoch 7671 mse 0.000566
epoch 7672 mse 0.000580
epoch 7673 mse 0.000574
epoch 7674 mse 0.000571
epoch 7675 mse 0.000567
epoch 7676 mse 0.000575
epoch 7677 mse 0.000567
epoch 7678 mse 0.000562
epoch 7679 mse 0.000585
epoch 7680 mse 0.000572
epoch 7681 mse 0.000574
epoch 7682 mse 0.000563
epoch 7683 mse 0.000566
epoch 7684 mse 0.000564
epoch 7685 mse 0.000566
epoch 7686 mse 0.000560
epoch 7687 mse 0.000570
epoch 7688 mse 0.000568
epoch 7689 mse 0.000563
epoch 7690 mse 0.000566
epoch 7691 mse 0.000572
epoch 7692 mse 0.000565
epoch 7693 mse 0.000578
epoch 7694 mse 0.000582
epoch 7695 mse 0.000564
epoch 7696 mse 0.000559
epoch 7697 mse 0.000577
epoch 7698 mse 0.000572
epoch 7699 mse 0.000566
epoch 7700 mse 0.000557
epoch 7701 mse 0.000587
epoch 7702 mse 0.000586
epoch 7703 mse 0.000588
epoch 7704 mse 0.000563
epoch 7705 mse 0.000563
epoch 7706 mse 0.000586
epoch 7707 mse 0.000581
epoch 7708 mse 0.000581
epoch 7709 mse 0.000567
epoch 7710 mse 0.000578
epoch 7711 mse 0.000567
epoch 7712 mse 0.000568
epoch 7713 mse 0.000573
epoch 7714 mse 0.000583
epoch 7715 mse 0.000572
epoch 7716 mse 0.000573
epoch 7717 mse 0.000575
epoch 7718 mse 0.000569
epoch 7719 mse 0.000573
epoch 7720 mse 0.000573
epoch 7721 mse 0.000577
epoch 7722 mse 0.000574
epoch 7723 mse 0.000569
epoch 7724 mse 0.000567
epoch 7725 mse 0.000574
epoch 7726 mse 0.000564
epoch 7727 mse 0.000561
epoch 7728 mse 0.000570
epoch 7729 mse 0.000571
epoch 7730 mse 0.000563
epoch 7731 mse 0.000565
epoch 7732 mse 0.000563
epoch 7733 mse 0.000578
epoch 7734 mse 0.000569
epoch 7735 mse 0.000572
epoch 7736 mse 0.000567
epoch 7737 mse 0.000571
epoch 7738 mse 0.000568
epoch 7739 mse 0.000564
epoch 7740 mse 0.000568
epoch 7741 mse 0.000564
epoch 7742 mse 0.000560
epoch 7743 mse 0.000572
epoch 7744 mse 0.000574
epoch 7745 mse 0.000564
epoch 7746 mse 0.000573
epoch 7747 mse 0.000571
epoch 7748 mse 0.000609
epoch 7749 mse 0.000581
epoch 7750 mse 0.000579
epoch 7751 mse 0.000609
epoch 7752 mse 0.000606
epoch 7753 mse 0.000576
epoch 7754 mse 0.000606
epoch 7755 mse 0.000605
epoch 7756 mse 0.000584
epoch 7757 mse 0.000575
epoch 7758 mse 0.000590
epoch 7759 mse 0.000567
epoch 7760 mse 0.000582
epoch 7761 mse 0.000575
epoch 7762 mse 0.000570
epoch 7763 mse 0.000572
epoch 7764 mse 0.000572
epoch 7765 mse 0.000574
epoch 7766 mse 0.000564
epoch 7767 mse 0.000568
epoch 7768 mse 0.000568
epoch 7769 mse 0.000585
epoch 7770 mse 0.000558
epoch 7771 mse 0.000571
epoch 7772 mse 0.000579
epoch 7773 mse 0.000565
epoch 7774 mse 0.000565
epoch 7775 mse 0.000583
epoch 7776 mse 0.000580
epoch 7777 mse 0.000569
epoch 7778 mse 0.000566
epoch 7779 mse 0.000574
epoch 7780 mse 0.000569
epoch 7781 mse 0.000564
epoch 7782 mse 0.000562
epoch 7783 mse 0.000574
epoch 7784 mse 0.000577
epoch 7785 mse 0.000564
epoch 7786 mse 0.000560
epoch 7787 mse 0.000573
epoch 7788 mse 0.000570
epoch 7789 mse 0.000565
epoch 7790 mse 0.000571
epoch 7791 mse 0.000597
epoch 7792 mse 0.000576
epoch 7793 mse 0.000578
epoch 7794 mse 0.000596
epoch 7795 mse 0.000569
epoch 7796 mse 0.000578
epoch 7797 mse 0.000565
epoch 7798 mse 0.000579
epoch 7799 mse 0.000572
epoch 7800 mse 0.000569
epoch 7801 mse 0.000576
epoch 7802 mse 0.000565
epoch 7803 mse 0.000563
epoch 7804 mse 0.000569
epoch 7805 mse 0.000563
epoch 7806 mse 0.000566
epoch 7807 mse 0.000573
epoch 7808 mse 0.000565
epoch 7809 mse 0.000563
epoch 7810 mse 0.000570
epoch 7811 mse 0.000569
epoch 7812 mse 0.000565
epoch 7813 mse 0.000561
epoch 7814 mse 0.000563
epoch 7815 mse 0.000572
epoch 7816 mse 0.000577
epoch 7817 mse 0.000567
epoch 7818 mse 0.000571
epoch 7819 mse 0.000566
epoch 7820 mse 0.000569
epoch 7821 mse 0.000569
epoch 7822 mse 0.000564
epoch 7823 mse 0.000571
epoch 7824 mse 0.000572
epoch 7825 mse 0.000572
epoch 7826 mse 0.000565
epoch 7827 mse 0.000570
epoch 7828 mse 0.000574
epoch 7829 mse 0.000570
epoch 7830 mse 0.000560
epoch 7831 mse 0.000579
epoch 7832 mse 0.000574

In [23]:
#@title 7) Optional: Quantum synchrony + Brian2 entrainment
import cirq, qsimcirq
from brian2 import *

class QuantumSynchrony:
    def __init__(self, n_qubits=4, depth=2):
        self.n_qubits=n_qubits; self.depth=depth
        self.qubits=cirq.LineQubit.range(n_qubits)
        self.sim=qsimcirq.QSimSimulator()
    def _reduce(self, e):
        x=np.tanh(np.asarray(e,dtype=np.float32))*np.pi
        x=x[:self.n_qubits]
        if x.size<self.n_qubits: x=np.pad(x,(0,self.n_qubits-x.size))
        return x
    def _circuit(self, x):
        c=cirq.Circuit()
        c.append([cirq.H(q) for q in self.qubits])
        for _ in range(self.depth):
            for i,q in enumerate(self.qubits):
                c.append(cirq.ry(x[i])(q)); c.append(cirq.rz(0.5*x[i])(q))
            for i in range(self.n_qubits-1):
                c.append(cirq.CZ(self.qubits[i], self.qubits[i+1]))
        return c
    def kernel(self, ea, eb):
        sa=self.sim.simulate(self._circuit(self._reduce(ea))).final_state_vector
        sb=self.sim.simulate(self._circuit(self._reduce(eb))).final_state_vector
        return float(np.abs(np.vdot(sa,sb))**2)

def plv_from_coupling(coupling=0.2, duration_ms=200):
    start_scope()
    eqs='''dphi/dt = omega + k*sin(phi_other - phi) : Hz
    phi_other : 1
    omega : Hz
    k : Hz'''
    G=NeuronGroup(2, eqs, method='euler')
    # G.phi should be unitless for phase, G.omega must be Hz as declared in eqs.
    G.phi=[0.1,2.0]; G.omega=[2*np.pi*8*Hz,2*np.pi*8*Hz]; G.k=coupling * Hz
    @network_operation(dt=1*ms)
    def couple():
        G.phi_other[0]=G.phi[1]; G.phi_other[1]=G.phi[0]
    M=StateMonitor(G,'phi',record=True)
    net=Network(G,couple,M); net.run(duration_ms*ms)
    phase_diff=np.array(M.phi[0]-M.phi[1])
    return float(np.abs(np.mean(np.exp(1j*phase_diff))))

qs=QuantumSynchrony()
print("qsync demo:", qs.kernel([0.2,0.1,0.6,0.4],[0.2,0.1,0.6,0.4]))
print("plv demo:", plv_from_coupling(0.05), plv_from_coupling(0.35))

qsync demo: 1.0000004768371582

DimensionMismatchError: phi should be set with a value with units hertz, but got [0.1 2. ] (unit is 1).

In [26]:
import torch, json
import numpy as np

MODEL_PATH = "/content/student_distilled_heads_hf.torchscript.pt"
NORM_PATH  = "/content/student_norm_hf.json"

model = torch.jit.load(MODEL_PATH)
model.eval()

with open(NORM_PATH) as f:
    norm = json.load(f)

mu = np.array(norm["mu"], dtype=np.float32)
sd = np.array(norm["sd"], dtype=np.float32)

def normalize(x):
    return (x - mu) / sd

def predict(feature_vector):
    x = normalize(np.array(feature_vector, dtype=np.float32))
    x = torch.tensor(x).unsqueeze(0)
    with torch.no_grad():
        y = model(x)
    return y.squeeze().numpy()